version: '3.7'
services:
  phpbb:
    # 3.2.3
    #image: 'bitnami/phpbb@sha256:4c2de5efac3373fb8df6f56be939ce71052df3668d53037a920b5a0594f42a04'
    # 3.3.0
    image: 'bitnami/phpbb@sha256:feee2dffd6206ab399082d1deb28908db954eddd009134c2220f9d19f72c9960'
    container_name: phpbb
    restart: always
    environment:
      # Gateway to host is found using `docker inspect <container-id-or-name> | grep Gateway`
      # For this to work, you need to do
      # CREATE USER 'phpbb'@'172.20.%' IDENTIFIED BY 'password';
      # GRANT ALL PRIVILEGES ON phpbb.* TO 'phpbb'@'172.20.%';
      MARIADB_HOST: "172.20.0.1"
      PHPBB_DATABASE_NAME: "phpbb"
      PHPBB_DATABASE_USER: "phpbb"
      PHPBB_FORUM_NAME: "simplicitypvp.net"
      PHPBB_FORUM_DESCRIPTION: "simpvp"
    env_file:
      - "phpbb_secrets.env"
    ports:
      - '4285:80'
    volumes:
      - type: bind
        source: '/srv/docker/phpbb'
        target: '/bitnami'



  # Need to run:
  # CREATE USER 'mediawiki'@'172.20.%' IDENTIFIED BY 'password';
  # GRANT ALL PRIVILEGES ON mediawiki.* TO 'mediawiki'@'172.20.%';
  mediawiki:
    # 1.32
    #image: 'mediawiki@sha256:349aeb8014b58754ac25ea022ee0c26e399ce18d756ecada7579c3f39d52c5a1'
    # 1.34
    #image: 'mediawiki@sha256:c3fa0aac98b741a40d9d40cf931d4e339578d02226d7f47f85a1270fee260bc4'
    build:
      context: /empty
      dockerfile: /root/mediawiki.Dockerfile
    container_name: mediawiki
    restart: always
    ports:
      - 4286:80
    volumes:
      - '/srv/docker/mediawiki/LocalSettings.php:/var/www/html/LocalSettings.php:ro'
      - '/srv/docker/mediawiki/.htaccess:/var/www/html/.htaccess:ro'
      - '/srv/docker/mediawiki/images/:/var/www/html/images'
      - '/srv/docker/mediawiki/extensions/:/var/www/html/extensions:ro'




  dfw:
    # 1.0.1
    image: "pitkley/dfw@sha256:7427e7379cb603d3e34580ee7f3ebd513dbfcdca97255bb0612cce7388bdcf62"
    container_name: dfw
    network_mode: host
    restart: always
    cap_add:
      - NET_ADMIN
    command:
      - "--config-file"
      - "/config"
        #- "--log-level"
        #- "trace"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/srv/config/nftables/dfw.fen.toml:/config"
    # This depends_on is a hack to just get it working because of the bug
    # where it can't apply rules if there aren't already any containers
    depends_on:
      - phpbb
