version: '3.7'
services:
  phpbb:
    # 3.2.3
    #image: 'bitnami/phpbb@sha256:4c2de5efac3373fb8df6f56be939ce71052df3668d53037a920b5a0594f42a04'
    # 3.3.0
    image: 'bitnami/phpbb@sha256:feee2dffd6206ab399082d1deb28908db954eddd009134c2220f9d19f72c9960'
    container_name: phpbb
    restart: always
    networks:
      website:
        ipv4_address: 10.137.10.5
    environment:
      # Gateway to host is found using `docker inspect <container-id-or-name> | grep Gateway`
      # For this to work, you need to do
      # CREATE USER 'phpbb'@'10.137.%' IDENTIFIED BY 'password';
      # GRANT ALL PRIVILEGES ON phpbb.* TO 'phpbb'@'10.137.%';
      PHPBB_DATABASE_NAME: "phpbb"
      PHPBB_DATABASE_USER: "phpbb"
      PHPBB_FORUM_NAME: "simplicitypvp.net"
      PHPBB_FORUM_DESCRIPTION: "simpvp"
      #NAMI_LOG_LEVEL: trace
    env_file:
      - "phpbb_secrets.secret"
    ports:
      - '4285:80'
    volumes:
      - type: bind
        source: '/home/web/simpvp_website/docker/volumes/phpbb'
        target: '/bitnami'
      - '/home/web/simpvp_website/docker/volumes/phpbb/secrets:/secrets:ro'

  # Need to run:
  # CREATE USER 'mediawiki'@'10.137.%' IDENTIFIED BY 'password';
  # GRANT ALL PRIVILEGES ON mediawiki.* TO 'mediawiki'@'10.137.%';
  mediawiki:
    # 1.32
    #image: 'mediawiki@sha256:349aeb8014b58754ac25ea022ee0c26e399ce18d756ecada7579c3f39d52c5a1'
    # 1.34
    #image: 'mediawiki@sha256:c3fa0aac98b741a40d9d40cf931d4e339578d02226d7f47f85a1270fee260bc4'
    build:
      context: /empty
      dockerfile: /root/mediawiki.Dockerfile
    networks:
      website:
        ipv4_address: 10.137.10.6
    container_name: mediawiki
    restart: always
    ports:
      - 4286:80
    volumes:
      - '/home/web/simpvp_website/docker/volumes/mediawiki/LocalSettings.php:/var/www/html/LocalSettings.php:ro'
      - '/home/web/simpvp_website/docker/volumes/mediawiki/secrets:/secrets:ro'
      - '/home/web/simpvp_website/docker/volumes/mediawiki/.htaccess:/var/www/html/.htaccess:ro'
      - '/home/web/simpvp_website/docker/volumes/mediawiki/images/:/var/www/html/images'
      - '/home/web/simpvp_website/docker/volumes/mediawiki/extensions/:/var/www/html/extensions:ro'

networks:
  website:
    ipam:
      config:
        - subnet: 10.137.0.0/16
          ip_range: 10.137.10.0/24
          gateway: 10.137.0.254



